# Generated by Django 2.2.1 on 2019-05-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_serviceProfile', '0003_remove_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='dt_creation',
            field=models.DateTimeField(),
        ),
    ]
