# Generated by Django 2.2.1 on 2019-05-12 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_serviceProfile', '0006_auto_20190511_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persondata',
            old_name='username',
            new_name='user',
        ),
    ]
