# Generated by Django 2.2.1 on 2019-05-12 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_serviceProfile', '0007_auto_20190512_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('geodiv', models.CharField(max_length=50)),
                ('sub_geodiv', models.CharField(max_length=50)),
                ('geo_place', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('num', models.IntegerField()),
                ('zip_code', models.IntegerField()),
                ('dt_creation', models.DateField(auto_now_add=True)),
                ('dt_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
