# Generated by Django 2.2.1 on 2019-05-12 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_serviceProfile', '0009_serviceprovider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='geo_place',
            new_name='geoplace',
        ),
    ]
