# Generated by Django 2.2.1 on 2019-05-12 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_serviceProfile', '0010_auto_20190512_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='username',
            new_name='user',
        ),
    ]
