# Generated by Django 2.2.1 on 2019-05-13 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_serviceProfile', '0012_auto_20190512_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category',
        ),
    ]
